use Bill_System;

call insertnewBill('SBN', 'ABOLISHING THE ROAD BOARD', '2017-12-04', 'AN ACT ABOLISHING THE ROAD BOARD AND TRANSFERRING ITS POWERS AND FUNCTIONS INCLUDING THE MANAGEMENT OF THE MOTOR VEHICLES USER’S CHARGE FUNDS TO THE DEPARTMENT OF PUBLIC WORKS AND HIGHWAYS (DPWH) AND TO THE DEPARTMENT OF TRANSPORTATION (DOTR), AMENDING FOR THE PURPOSE REPUBLIC ACT NO. 8794, OTHERWISE KNOWN AS THE MOTOR VEHICLES USER’S CHARGE', 'National', 'Aquilino', 'L', 'Pimentel', 'Passed','Pending', 'Pending');

call insertnewBill('SBN','ANTI-DISCRIMINATION ACT OF 2017',	'2016-02-12','AN ACT PROHIBITING DISCRIMINATION ON THE BASIS OF ETHNICITY, RACE, RELIGION OR BELIEF, SEX, GENDER, SEXUAL ORIENTATION, GENDER IDENTITY, GENDER EXPRESSION, CIVIL STATUS AND HIV STATUS, AND PROVIDING PENALTIES THEREFOR',	'National', 'Aquilino', 'L', 'Pimentel', 'Pending',	'Pending',	'Pending');

call insertnewBill('HBN',	'ANTI-GRAFT AND CORRUPT PRACTICES ACT','2017-10-09',	'AN ACT AMENDING SECTION 13 OF REPUBLIC ACT NO. 3019, AS AMENDED, ENTITLED THE ''ANTI-GRAFT AND CORRUPT PRACTICES ACT''',	'National', 'Abad', 'R', 'Henedina', 'Pending',	'Pending',	'Pending');

call insertnewBill('SBN','REVERSION TO MAIDEN NAME ACT',	'2016-08-19',	'AN ACT ALLOWING WOMEN TO REVERT TO THEIR MAIDEN SURNAME, ESTABLISHING A PROCEDURE FOR REVERSION AND APPROPRIATING FUNDS THEREFORE',	'National', 'Ralph', 'G', 'Recto','Passed', 'Passed', 	'Pending');

call insertnewBill('HBN',	'GENERAL APPROPRIATIONS ACT, FY 2018',	'2015-08-28',	'AN ACT APPROPRIATING FUNDS FOR THE OPERATION OF THE GOVERNMENT OF THE REPUBLIC OF THE PHILIPPINES FROM JANUARY ONE TO DECEMBER THIRTY-ONE, TWO THOUSAND AND EIGHTEEN, AND FOR OTHER PURPOSES',	'National', 'Francis Gerald', 'A', 'Abaya', 'Passed',	'Passed',	'Pending');

call insertnewBill('HBN',	'BATAAN FOUNDATION DAY',	'2016-10-08',	'AN ACT DECLARING JANUARY 11 OF EVERY YEAR A SPECIAL NONWORKING HOLIDAY IN THE PROVINCE OF BATAAN IN COMMEMORATION OF ITS FOUNDING ANNIVERSARY TO BE KNOWN AS BATAAN FOUNDATION DAY',	'Local', 'Francis Gerald', 'A', 'Abaya', 'Pending',	'Pending',	'Pending');

call insertnewBill('HBN',	'PHILIPPINE BROADCASTING CORPORATION',	'2017-12-12',	'AN ACT EXTENDING FOR ANOTHER TWENTY-FIVE (25) YEARS THE FRANCHISE GRANTED TO PHILIPPINE BROADCASTING CORPORATION UNDER REPUBLIC ACT NO. 7962, ENTITLED AN ACT GRANTING THE PHILIPPINE BROADCASTING CORPORATION A FRANCHISE TO CONSTRUCT, INSTALL, OPERATE AND MAINTAIN RADIO AND TELEVISION BROADCASTING STATIONS WITHIN THE PHILIPPINES, AND FOR OTHER PURPOSES',	'Local', 'Raneo', 'E', 'Abu','Pending',	'Pending',	'Pending');

call insertnewBill('SBN',' DAVAO ORIENTAL STATE UNIVERSITY',	'2017-06-08', 'AN ACT CONVERTING THE DAVAO ORIENTAL STATE COLLEGE OF SCIENCE AND TECHNOLOGY IN THE CITY OF MATI AND ALL ITS SATELLITE CAMPUSES LOCATED IN THE PROVINCE OF DAVAO ORIENTAL INTO A STATE UNIVERSITY TO BE KNOWN AS THE DAVAO ORIENTAL STATE UNIVERSITY, INTEGRATING THEREWITH THE GOVERNOR GENEROSO COLLEGE OF ARTS, SCIENCE AND TECHNOLOGY IN THE MUNICIPALITY OF GOVERNOR GENEROSO, PROVINCE OF DAVAO ORIENTAL AND APPROPRIATING FUNDS THEREFOR',	'National', 'Vicente', 'C', 'Sotto', 'Pending','Pending',	'Pending');

call insertnewBill('SBN', 'OSG CHARTER',	'2017-12-01',	'AN ACT FURTHER STRENGTHENING THE OFFICE OF THE SOLICITOR GENERAL BY INCREASING ITS POWERS AND FUNCTIONS, AND REDEFINING, EXPANDING, AND RATIONALIZING ITS ORGANIZATION, REPEALING FOR THE PURPOSE REPUBLIC ACT NO. 9417, REPUBLIC ACT NO. 2327, AND EXECUTIVE ORDER NOS. 1 AND 2, S. 1986, APPROPRIATING FUNDS THEREFOR AND FOR OTHER PURPOSES',	'Local', 'Vicente', 'C', 'Sotto', 'Pending',	'Pending',	'Pending');


call insertnewBill('HBN', 	'MANLILISID NATIONAL HIGH SCHOOL',	'2017-08-18', 	'AN ACT ESTABLISHING A NATIONAL HIGH SCHOOL IN BARANGAY MANLILISID, MUNICIPALITY OF JAVIER, PROVINCE OF LEYTE TO BE KNOWN AS MANLILISID NATIONAL HIGH SCHOOL AND APPROPRIATING FUNDS THEREFOR',	'Local', 'Rodrigo', 'A', 'Abellanosa','Passed',	'Pending',	'Pending');

call insertnewBill('HBN',	'NATIONAL TECHNICAL-VOCATIONAL DAY',	'2017-09-08',	'AN ACT DECLARING THE TWENTY-FIFTH DAY OF AUGUST OF EVERY YEAR AS THE NATIONAL TECHNICAL-VOCATIONAL DAY',	'National', 'Rodrigo', 'A', 'Abellanosa', 'Passed',	'Passed',	'Passed');

call insertnewBill('HBN',	'SARANGGANI SPORTS TRAINING CENTER,',	'2017-06-27',	'AN ACT ESTABLISHING THE SARANGANI SPORTS TRAINING CENTER IN THE MUNICIPALITY OF ALABEL, PROVINCE OF SARANGANI AND APPROPRIATING FUNDS THEREFOR',	'Local', 'Rodrigo', 'A', 'Abellanosa', 'Pending',	'Pending',	'Pending');

call insertnewBill('HBN', 'PUBLIC UTILITY VEHICLE MONITORING ACT',	'2016-09-01',	'AN ACT MANDATING THE INSTALLATION OF SAFETY MONITORING DEVICES IN PUBLIC UTILITY VEHICLES AND PROVIDING PENALTIES FOR VIOLATION THEREOF',	'National', 'Abad', 'R', 'Henedina','Passed',	'Pending',	'Pending');

call insertnewBill('SBN', 'CONSTITUTIONAL EDUCATION ACT',	'2017-10-10',	'AN ACT INTEGRATING EDUCATION ON THE 1987 CONSTITUTION OF THE REPUBLIC OF THE PHILIPPINES IN THE GRADE 12 SENIOR HIGH SCHOOL CURRICULA OF ALL PUBLIC AND PRIVATE EDUCATIONAL INSTITUTIONS',	'National', 'Sonny', 'M', 'Angara', 'Passed',	'Passed',	'Passed');

call insertnewBill('SBN', 'PNP MODERNIZATION ACT OF 2017',	'2017-08-04',	'AN ACT PROVIDING FOR THE MODERNIZATION OF THE PHILIPPINE NATIONAL POLICE, APPROPRIATING FUNDS THEREFOR, AND FOR OTHER PURPOSES',	'National', 'Sonny', 'M', 'Angara','Pending',	'Pending',	'Pending');

call insertnewBill('SBN', 'GIFT CHECK ACT OF 2017',	'2017-05-03',	'AN ACT PROHIBITING THE IMPOSITION OF EXPIRY DATES ON GIFT CHECKS, CERTIFICATES OR CARDS BY ISSUERS AND FOR OTHER PURPOSES',	'National', 'Paolo Benigno', 'V', 'Aquino','Passed',	'Passed',	'Passed');

call insertnewBill('SBN', 'PHILIPPINE CHARITY OFFICE ACT OF 2017',	'2016-03-09',	'AN ACT CREATING THE PHILIPPINE CHARITY OFFICE',	'National', 'Paolo Benigno', 'V', 'Aquino','Passed',	'Passed',	'Pending');

call insertnewBill('SBN', 'MATERNITY LEAVE MONETIZATION ACT',	'2017-09-10',	'AN ACT ALLOWING THE MONETIZATION OF MATERNITY LEAVE CREDITS OF FEMALE EMPLOYEES AND THE COVERED SOCIAL SECURITY SYSTEM (SSS) FEMALE MEMBERS, AND FOR OTHER PURPOSES',	'National', 'Paolo Benigno', 'V', 'Aquino', 'Passed',	'Passed',	'Pending');

call insertnewBill('HBN',	'SAN ANTONIO NATIONAL HIGH SCHOOL PARANAQUE',	'2017-08-06', 'AN ACT SEPARATING THE PARANAQUE NATIONAL HIGH SCHOOL - SAN ANTONIO HIGH SCHOOL ANNEX IN BARANGAY SAN ANTONIO, PARANAQUE CITY, FROM THE PARANAQUE NATIONAL HIGH SCHOOL, CONVERTING IT INTO AN INDEPENDENT NATIONAL HIGH SCHOOL TO BE KNOWN AS SAN ANTONIO NATIONAL HIGH SCHOOL PARANAQUE, AND APPROPRIATING FUNDS THEREFOR',	'Local', 'Raneo', 'E', 'Abu', 'Passed',	'Pending',	'Pending');

call insertnewBill('HBN', 'DON BOSCO NATIONAL HIGH SCHOOL', '2017-08-08', 'AN ACT SEPARATING THE PARANAQUE NATIONAL HIGH SCHOOL- DON BOSCO EXTENSION IN BARANGAY DON BOSCO, PARANAQUE CITY, FROM THE PARANAQUE NATIONAL HIGH SCHOOL, CONVERTING IT INTO AN INDEPENDENT NATIONAI. HIGH SCHOOL TO BE KNOWN AS DON BOSCO NATIONAL HIGH SCHOOL AND APPROPRIATING FUNDS THEREFOR', 'Local', 'Raneo', 'E', 'Abu', 'Passed', 'Pending', 'Pending');