use Bill_System;

call insertnewSenator("Senator", "Jose", "D", "Ledesma", "Rm. 78 & 8 GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Member", "232-6575", "348-7976", "ledesmajose@gmail.com", "www.ledesmajose.ph" );
call insertnewHouseMember("House Member", "Damian", "G", "Mercado", "Quezon City", "Isabela", "4th", "931 55 07", "931 50 01" );
call insertnewSenator("Senator", "Robert", "Z", "Barbers", "Rm. 403 & 15 GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Enforcer", "932-4356", "552-6601", "barbers@gmail.com", "www.barbers.com" );
call insertnewSenator("Senator", "Francisco", "B", "Villanueva", "Rm. 236 & 15 GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Member", "932-4356", "232-2342", "franciscoV@gmail.com", "www.franciscoVill.ph" );
call insertnewSenator("Senator", "Isabelo", "H", "Reyes", "Rm. 76 & 67 (New Wing 5/F) GSIS Bldg., Financial Center, Diokno Blvd., Pasay City", "Member", "232-6575", "345-2154", "isabeloReyes@gmail.com", "www.isabeloReyes.ph" );
call insertnewSenator("Senator", "Panfilo", "M", "Lacson", "Room 602 (Extension at Room 17, New Wing, 5/F), GSIS Bldg., Financial Center, Diokno Blvd., Pasay City", "Member", " ", "552-6601", "ospml@yahoo.com", "www.pinglacson.net" );
call insertnewHouseMember("House Member", "Carmelo", "B", "Lazatin II", "Quezon City", "Pampanga", "1st", "931 54 84", "931 50 01" );
call insertnewSenator("Senator", "Rafael", "E", "Palma", "Rm. 203 & 09 GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Member", "632-4523", "423-9767", "Rpalma@gmail.com", "www.PalmaRafael.ph" );
call insertnewHouseMember("House Member", "Rodolfo", "T", "Albano III", "Quezon City", "Isabela", "1st", "931 61 69", "931 50 01" );
call insertnewHouseMember("House Member", "Rodolfo", "C", "Fariñas", "Quezon City", "Ilocos Norte", "1st", "442 41 15", "931 50 01" );
call insertnewSenator("Senator", "Raul", "S", "Roco", "Rm. 601 & 20 (New Wing 5/F) GSIS Bldg., Financial Center, Diokno Blvd., Pasay City", "Member", "345-6957", "552-6601", "roco@gmail.com", "www.narcocom" );
call insertnewHouseMember("House Member", "Teddy", "B", "Baguilat", "Quezon City", "Ifuago", "Lone", "931 51 06", "931 50 01" );
call insertnewHouseMember("House Member", "Rachel", "B", "Del Mar", "Quezon City", "Negros Occidental", "2nd", "931 56 38", "931 50 01" );
call insertnewSenator("Senator", "Cynthia", "A", "Villar", "Rm. 503 GSIS Bldg., Financial Center, Diokno Blvd., Pasay City", "Member", "552-6715", "552-6601", "sencynthiavillar@gmail.com", "www.cynthiavillar.com.ph" );
call insertnewHouseMember("House Member", "Vicente", "J", "Alcala", "Quezon City", "Quezon", "2nd", "442 42 62", "931 50 01" );
call insertnewSenator("Senator", "Paolo", "B", "Aquino IV", "Rm. 510 & 5 (New Wing 5/F) GSIS Bldg., Financial Center, Diokno Blvd., Pasay City", "Assistant Minority Leader", "552-6747", "552 6601", "team.bamaquino@senado.ph", "www.facebook.com/BenignoBamAquino" );
call insertnewSenator("Senator", "Aquillino", "L", "Pimentel III", "Rm. 606-609 & 1 (New Wing 5/F) GSIS Bldg., Financial Center, Diokno Blvd., Pasay City", "President", "822-9758", "552-6601", "kokopimenteloffice@yahoo.com", "www.kokopimentel.org" );
call insertnewSenator("Senator", "Kiko", "P", "Pangilinan", "Rm. 502 5th Flr., GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Member", "552-6732", "552-6601", "kilosko2004@yahoo.com", "www.kiko.ph" );
call insertnewSenator("Senator", "Mariano", "O", "Yulo", "Rm. 818 & 15 GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Member", "348-7976", "678-2342", "yuloM@gmail.com", "www.yuloM.ph" );
call insertnewHouseMember("House Member", "Leopoldo", "N", "Bataoil", "Quezon City", "Pangasinan", "2nd", "931 59 64", "931 50 01" );
call insertnewHouseMember("House Member", "Oscar", "G", "Malapitan", "Quezon City", "Manila", "4th", "931 51 15", "931 50 01" );
call insertnewHouseMember("House Member", "Ibarra", "M", "Gutierrez III", "Quezon City", "Davao City", "2nd", "931 61 60", "931 50 01" );
call insertnewSenator("Senator", "Agapito", "A", "Aquino", "Rm. 76 & 67 (New Wing 5/F) GSIS Bldg., Financial Center, Diokno Blvd., Pasay City", "Member", "686-6957", "552-6601", "acquino@rocketmail.com", "www.acquino.ph" );
call insertnewHouseMember("House Member", "Manuel Jose", "M", "Dalipe", "Quezon City", "Zamboanga City", "2nd", "931 59 88", "931 50 01" );
call insertnewHouseMember("House Member", "Joseph Gilbert", "F", "Violago", "Quezon City", "Nueva Ecija", "3rd", "931 61 13", "931 50 01" );
call insertnewHouseMember("House Member", "Zajid", "G", "Mangudadatu", "Quezon City", "Maguindanao", "2nd", "951 10 88", "931 50 01" );
call insertnewHouseMember("House Member", "Marlyn", "L", "Primicias-Agabas", "Quezon City", "Pangasinan", "6th", "931 52 65", "931 50 01" );
call insertnewSenator("Senator", "Manny", "F", "Villar", "Rm. 503 5th Flr., GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Member", "552-6715", "552-6601", "mb_villar@yahoo.com", "www.mannyvillar.com.ph" );
call insertnewHouseMember("House Member", "Delphine", "G", "Lee", "Quezon City", "Lanao del Sur", "1st", "931 66 45", "931 50 01" );
call insertnewSenator("Senator", "Juan", "B", "Sumulong", "Rm. 56 & 67 GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Member", "686-6957", "242-3453", "juansumulong@gmail.com", "www.juansumulong.ph" );
call insertnewHouseMember("House Member", "Tobias", "M", "Tiangco", "Quezon City", "Navotas City", "Lone", "442 40 29", "931 50 01" );
call insertnewSenator("Senator", "Pedro", "D", "Guzman", "Rm. 543 & 8 GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Member", "234-4301", "234-6786", "pedroguzman@gmail.com", "www.pedroguzman.ph" );
call insertnewSenator("Senator", "Ralph", "G", "Recto", "Rm. 509 & 19 (New Wing 5/F) GSIS Bldg., Financial Center, Diokno Blvd., Pasay City", "President Pro-Tempore", "659-5756", "552-6601", "ralphgrecto@gmail.com", "www.ralphrecto.ph" );
call insertnewHouseMember("House Member", "Munir", "M", "Arbison", "Quezon City", "Sulu", "2nd", "931 62 68", "931 50 01" );
call insertnewHouseMember("House Member", "Edgar Mary", "S", "Sarmiento", "Quezon City", "Samar", "1st", "951 89 19", "931 50 01" );
call insertnewHouseMember("House Member", "Alfredo", "B", "Benitez", "Quezon City", "Manila", "5th", "951 09 18", "931 50 01" );
call insertnewHouseMember("House Member", "Sherwin", "N", "Tugna", "Quezon City", "Camarines Norte", "1st", "951 08 93", "931 50 01" );
call insertnewHouseMember("House Member", "Rolando", "G", "Andaya Jr", "Quezon City", "Camarines Sur", "1st", "952 48 58", "931 50 01" );
call insertnewSenator("Senator", "Luisa", "P", "Estrada", "Rm. 507 & 13 (New Wing 5/F) GSIS Bldg., Financial Center, Diokno Blvd., Pasay City", "Member", "833-6257", "552-6601", "luisa@gmail.com", "www.luiza.com" );
call insertnewHouseMember("House Member", "Giorgidi", "B", "Aggabao", "Quezon City", "Bukidnon", "1st", "951 12 23", "931 50 01");
call insertnewHouseMember("House Member", "Rozzano Rufino", "B", "Biazon", "Quezon City", "Muntinlupa", "Lone", "442 42 05", "931 50 01" );
call insertnewHouseMember("House Member", "Feliciano", "R", "Belmonte", "Quezon City", "Dinagat Islands", "Lone", "931 98 38", "931 50 01" );
call insertnewSenator("Senator", "Antonio", "R", "Belo", "Rm. 343 & 45 GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Member", "786-5432", "343-2342", "beloantonio@gmail.com", "www.beloantonio.ph" );
call insertnewSenator("Senator", "Leticia", "R", "Shahani", "Rm. 32 & 7 (New Wing 5/F) GSIS Bldg., Financial Center, Diokno Blvd., Pasay City", "Member", "312-4215", "552-6601", "leticia@up.edu.ph", "www.letty.com.ph" );
call insertnewHouseMember("House Member", "Homer", "G", "Rift", "Quezon City", "Cagayan", "3rd", "951 89 57", "931 50 01" );
call insertnewSenator("Senator", "Juan", "R", "Alegre", "Rm. 231 & 45 GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Member", "786-5432", "343-2342", "juanalegru@gmail.com", "www.juanalegru.ph" );
call insertnewSenator("Senator", "Hermenegildo", "U", "Villanueva", "Rm. 236 & 15 GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Member", "4564-4356", "234-2342", "hermenegildovillanueva@gmail.com", "www.hervillanueva.ph" );
call insertnewSenator("Senator", "Orlando", "S", "Mercado", "Rm. 678 & 7 (New Wing 5/F) GSIS Bldg., Financial Center, Diokno Blvd., Pasay City", "Member", "342-4645", "552-6601", "orlandolright@rocketmail.com", "orlandomagic.com" );
call insertnewSenator("Senator", "Pedro", "D", "Guevara", "Rm. 543 & 06 GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Member", "342-4301", "342-2342", "guevarapedro@gmail.com", "www.guevarapedro.ph" );
call insertnewSenator("Senator", "Franklin", "M", "Drilon", "Rm. 601 & 20 (New Wing 5/F) GSIS Bldg., Financial Center, Diokno Blvd., Pasay City", "President", "833-6257", "552-6601", "os_frankdrilon@yahoo.com", "www.drilon.ph" );
call insertnewSenator("Senator", "Robert", "S", "Jaworski", "Rm. 527 5th Flr., GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Member", "435-4301", "552-6601", "greatestplayer@gmail.com", "www.jaworski.ph" );
call insertnewHouseMember("House Member", "Juan Edgardo", "M", "Angara", "Quezon City", "Aurora", "Lone", "931 56 42", "931 50 01" );
call insertnewHouseMember("House Member", "Jose Carlos", "L", "Cari", "Quezon City", "Leyte", "5th", "931 51 54", "931 50 01" );
call insertnewHouseMember("House Member", "Jorge", "T", "Almonte", "Quezon City", "Misamis Occidental", "1st", "931 62 29", "931 50 01" );
call insertnewSenator("Senator", "Leila", "M", "De Lima", "Rm. 502 & 16 (New Wing 5/F) GSIS Bldg., Financial Center, Diokno Blvd., Pasay City", "Member", "807-8489", "552-6601", "senleilamdelima@gmail.com", " " );
call insertnewSenator("Senator", "Gregorio", "B", "Honasan", "Rm. 507 & 13 (New Wing 5/F) GSIS Bldg., Financial Center, Diokno Blvd., Pasay City", "Member", "833-6257", "552-6601", "gringobhonasan@gmail.com", "www.gringohonasan.ph" );
call insertnewHouseMember("House Member", "Ronald", "M", "Cosalan", "Quezon City", "Benguet", "Lone", "931 60 74", "931 50 01" );
call insertnewHouseMember("House Member", "Antonio", "A", "Del Rosario", "Quezon City", "Taguig City-Pateros", "1st", "931 56 91", "931 50 01" );
call insertnewHouseMember("House Member", "Joaquin", "M", "Chipeco", "Quezon City", "Laguna", "2nd", "931 57 35", "931 50 01" );
call insertnewSenator("Senator", "Tomas", "M", "Gomez", "Rm. 32 & 09 GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Member", "632-678", "786-5432", "gomeztomas@gmail.com", "www.gomeztomas.ph" );
call insertnewHouseMember("House Member", "Luis Raymund", "F", "Villafuerte", "Quezon City", "Camarines Sur", "2nd", "931 67 18", "931 50 01" );
call insertnewHouseMember("House Member", "Elisa", "H", "Kho", "Quezon City", "Masbate", "2nd", "931 65 27", "931 50 01" );
call insertnewHouseMember("House Member", "Rufus", "B", "Rodriguez", "Quezon City", "Cagayan de Oro City", "2nd", "931 62 21", "931 50 01" );
call insertnewHouseMember("House Member", "Erlpe John", "M", "Alvarez", "Quezon City", "Agusan del Norte", "2nd", "931 56 15", "931 50 01" );
call insertnewSenator("Senator", "Antonio", "F", "Trillanes IV", "Rm. 519 & 15 (New Wing 5/F) GSIS Bldg., Financial Center, Diokno Blvd., Pasay City", "Member", "833-6257", "552-6601", "senateoffice@trillanes.com.ph", "www.trillanes.com.ph" );
call insertnewSenator("Senator", "Bernabe", "P", "Guingona", "Rm. 234 & 13 (New Wing 5/F) GSIS Bldg., Financial Center, Diokno Blvd., Pasay City", "Member", "686-6957", "632-678", "bernabeguianoa@gmail.com", "www.bernabeguianoa.ph" );
call insertnewHouseMember("House Member", "Geraldine", "B", "Roman", "Quezon City", "Bataan", "1st", "931 56 20", "931 50 01" );
call insertnewSenator("Senator", "Ernesto", "O", "Herrera", "Rm. 345 & 45 GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Member", "312-4215", "552-6601", "ernest@yahoo.com", "www.ernest.net.ph" );
call insertnewSenator("Senator", "Edgardo", "M", "Angara", "Rm. 521-A 5/F GSIS Bldg., Financial Center, Diokno Blvd., Pasay City", "Member", "552-6779", "552-6601", "sensonnyangara@yahoo.com", "fb.com/sonnyangara" );
call insertnewHouseMember("House Member", "Doy", "C", "Leachon", "Quezon City", "Zamboanga del Norte", "1st", "931 53 95", "931 50 01" );
call insertnewSenator("Senator", "Santiago", "Q", "Lucero", "Rm. 32 & 7 (New Wing 5/F) GSIS Bldg., Financial Center, Diokno Blvd., Pasay City", "Member", "353-4645", "686-6957", "santiagoLucero@gmail.com", "www.santiagoLucero.ph" );
call insertnewSenator("Senator", "Alfredo", "S", "Lim", "Rm. 503 GSIS Bldg., Financial Center, Diokno Blvd., Pasay City", "Member", "552-6688", "552-6601", "lim@gmail.com", "www.limthekiller.com" );
call insertnewHouseMember("House Member", "Karlo", "B", "Nograles", "Quezon City", "Manila", "3rd", "931 55 01", "931 50 01" );
call insertnewSenator("Senator", "Ramon", "B", "Revilla", "Rm. 506 & 8 GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Member", "552-6776", "552-6601", "rbongrevillajr@yahoo.com", "www.ramonbongrevillajr.com" );
call insertnewSenator("Senator", "Noli", "L", "De Castro", "Rm. 503 & 15 GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Member", "234-6957", "552-6601", "kabayan@gmail.com", "kabayan.com.ph" );
call insertnewHouseMember("House Member", "Celso", "L", "Lobregat", "Quezon City", "Zamboanga City", "1st", "951 89 47", "931 50 01" );
call insertnewSenator("Senator", "Celestino", "K", "Rodriguez", "Rm. 525 & 7 (New Wing 5/F) GSIS Bldg., Financial Center, Diokno Blvd., Pasay City", "Member", "345-6957", "432-2154", "celestinoR@gmail.com", "www.celestinoR.ph" );
call insertnewHouseMember("House Member", "Anthony", "G", "Del Rosario", "Quezon City", "Zamboanga del Sur", "2nd", "951 88 89", "931 50 01" );
call insertnewSenator("Senator", "Jose", "B", "Hontiveros", "Rm. 565 & 67 GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Member", "234-4334", "234-4301", "hontiverosjose@gmail.com", "www.hontiverosjose.ph" );
call insertnewSenator("Senator", "Jose", "Q", "Vera", "Rm. 342 & 7 (New Wing 5/F) GSIS Bldg., Financial Center, Diokno Blvd., Pasay City", "Member", "678-2342", "686-6957", "joseVera@gmail.com", "www.joseVera.ph" );
call insertnewHouseMember("House Member", "Dakila Carlo", "E", "Cua", "Quezon City", "Quirino", "Lone", "931 51 02", "931 50 01" );
call insertnewHouseMember("House Member", "Vincent", "P", "Crisologo", "Quezon City", "Quezon City", "1st", "442 41 54", "931 50 01" );
call insertnewSenator("Senator", "Victor", "S", "Ziga", "Rm. 231 & 45 GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Member", "786-5432", "343-2342", "zigame@gmail.com", "www.sigagame.ph" );
call insertnewSenator("Senator", "Maria Lourdes Nancy", "S", "Binay", "Rm. 523 & 14 (New Wing 5/F) GSIS Bldg., Financial Center, Diokno Blvd., Pasay City", "Member", "502-9477", "552-6601", "binaynancy2013@yahoo.com", "www.facebook.com/SenatorNancyBinay" );
call insertnewHouseMember("House Member", "Magnolia", "C", "Antonino", "Quezon City", "Nueva Ecija", "4th", "931 60 42", "931 50 01" );
call insertnewHouseMember("House Member", "Gil", "P", "Acosta", "Quezon City", "Basilan", "Lone", "931 54 35", "931 50 01" );
call insertnewSenator("Senator", "Anna Dominique", "L", "Coseteng", "Rm. 32 & 09 GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Member", "345-6957", "552-6601", "coseteng@gmail.com", "www.corset.com.ph" );
call insertnewHouseMember("House Member", "Emmanuel", "A", "Billones", "Quezon City", "Capiz", "1st", "931 67 33", "931 50 01" );
call insertnewHouseMember("House Member", "Mark", "O", "Go", "Quezon City", "Baguio City", "Lone", "931 55 28", "931 50 01" );
call insertnewSenator("Senator", "Sherwin", "T", "Gatchallan", "Rm. 512 & 22 (New Wing 5/F) GSIS Bldg., Financial Center, Diokno Blvd., Pasay City", "Member", " ", "552-6601", "email@wingatchalian.com ", "www.wingatchalian.com" );
call insertnewHouseMember("House Member", "Ferdinand", "L", "Hernandez", "Quezon City", "Bataan", "2nd", "931 58 91", "931 50 01" );
call insertnewSenator("Senator", "Santiago", "D", "Fonacier", "Rm. 678 & 7 (New Wing 5/F) GSIS Bldg., Financial Center, Diokno Blvd., Pasay City", "Member", "234-4343", "423-2344", "fonacierSantiago@gmail.com", "www.fonacierSantiago.ph" );
call insertnewSenator("Senator", "Deb", "Z", "Cantrell", "Rm. 606-609 & 1 (New Wing 5/F) GSIS Bldg., Financial Center, Diokno Blvd., Pasay City", "Member", "552-6694", "552-6601", "cantrell@gmail.com", "www.cantrell.com" );
call insertnewHouseMember("House Member", "Pantaleon", "D", "Alvarez", "Quezon City", "Davao del Norte", "1st", "931 62 77", "931 50 01" );
call insertnewSenator("Senator", "John Henry", "R", "Osmeña", "Rm. 403 & 15 GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Member", "345-6957", "552-6601", "senate.john@gmail.com", "www.henry.ph" );
call insertnewHouseMember("House Member", "Erico Aristotle", "C", "Aumentado", "Quezon City", "Bohol", "2nd", "931 58 19", "931 50 01" );
call insertnewHouseMember("House Member", "Imelda", "R", "Marcos", "Quezon City", "Agusan del Sur", "2nd", "931 65 09", "931 50 01" );
call insertnewHouseMember("House Member", "Sol", "O", "Aragones", "Quezon City", "Laguna", "3rd", "931 562 05", "931 50 01" );
call insertnewSenator("Senator", "Jose Ma", "L", "Veloso", "Rm. 452 & 15 GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Member", "348-4301", "232-2342", "josemavillamor@gmail.com", "www.velosoJose.ph" );
call insertnewHouseMember("House Member", "Loreto Leo", "S", "Ocampos", "Quezon City", "Manila", "6th", "442 38 93", "931 50 01" );
call insertnewHouseMember("House Member", "Emmanuel", "F", "Madrona", "Quezon City", "Romblon", "Lone", "931 52 70", "931 50 01" );
call insertnewHouseMember("House Member", "Gina", "P", "De Venecia", "Quezon City", "Laguna", "4th", "931 53 69", "931 50 01" );
call insertnewSenator("Senator", "Ramon", "B", "Magsaysay Jr", "Rm. 507 & 13 (New Wing 5/F) GSIS Bldg., Financial Center, Diokno Blvd., Pasay City", "Member", "552-6732", "552-6601", "rmnmagsaysay@gmail.com", "www.ramonmag.com" );
call insertnewHouseMember("House Member", "Paolo Everardo", "S", "Javier", "Quezon City", "Antique", "Lone", "931 55 42", "931 50 01" );
call insertnewSenator("Senator", "Richard", "J", "Gordon", "Rm. 504 & 3 (New Wing 5/F) GSIS Bldg., Financial Center, Diokno Blvd., Pasay City", "Member", " ", "552-6776", "senatorrichardgordon@gmail.com", "www.dickgordon.ph" );
call insertnewHouseMember("House Member", "Edwin", "C", "Ong", "Quezon City", "Northern Samar", "2nd", "931 53 25", "931 50 01" );
call insertnewHouseMember("House Member", "Robert Ace", "S", "Barbes", "Quezon City", "Surigao del Norte", "2nd", "442 41 51", "931 50 01");
call insertnewSenator("Senator", "Marcelo", "B", "Fernan", "Rm. 345 & 13 (New Wing 5/F) GSIS Bldg., Financial Center, Diokno Blvd., Pasay City", "Member", "632-2467", "552-6601", "fernan@yahoo.com", "www.briones.ph" );
call insertnewSenator("Senator", "Manuel", "M", "Lapid", "Rm. 516 GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Member", "552-6694", "552-6601", "senmanuellapid@yahoo.com.ph", "litolapid.net" );
call insertnewHouseMember("House Member", "Eric", "M", "Martinez", "Quezon City", "Valenzuela City", "2nd", "931 73 27", "931 50 01" );
call insertnewSenator("Senator", "Grace", "L", "Poe", "Rm. 525 & 7 (New Wing 5/F) GSIS Bldg., Financial Center, Diokno Blvd., Pasay City", "Member", "833-6257", "552-6601", "gracepoe2013@gmail.com", "www.gracepoe.ph" );
call insertnewHouseMember("House Member", "Gabriel", "H", "Bordado", "Quezon City", "Camarines Sur", "3rd", "931 58 32", "931 50 01" );
call insertnewSenator("Senator", "Jamby", "A", "Madrigal", "Rm. 510 5th flr., GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Member", "552-6703", "552-6601", "mam@senate.gov.ph", "www.jambymadrigal.com" );
call insertnewSenator("Senator", "Filemon", "P", "Sotto", "Rm. 432 & 7 (New Wing 5/F) GSIS Bldg., Financial Center, Diokno Blvd., Pasay City", "Member", "342-6957", "552-2154", "filemon@gmail.com", "www.filemonfilemon.ph" );
call insertnewHouseMember("House Member", "Peter John", "D", "Calderon", "Quezon City", "Cebu", "7th", "931 63 24", "931 50 01" );
call insertnewHouseMember("House Member", "Jesus Emmanuel", "M", "Paras", "Quezon City", "Surigao del Sur", "2nd", "931 58 68", "931 50 01" );
call insertnewSenator("Senator", "Jose", "U", "Laurel", "Rm. 68 & 67 GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Member", "242-3453", "234-2342", "LaurelJose@gmail.com", "www.LaurelJose.ph" );
call insertnewSenator("Senator", "Sergio", "H", "Osmena", "Rm. 46 & 67 (New Wing 5/F) GSIS Bldg., Financial Center, Diokno Blvd., Pasay City", "Member", "232-6575", "345-2154", "sergioOsmena@gmail.com", "www.sergioOsmena.ph" );
call insertnewSenator("Senator", "Mar", "A", "Roxas", "Rm. 523 5th Flr., GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Member", "552-6688", "552-6601", "mar@marroxas.com", "www.marroxas.com" );
call insertnewSenator("Senator", "Joker", "P", "Arroyo", "Rm 511 5th Flr., GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Member", "552-6730", "552-6601", "jokerarroyo@yahoo.com", "www.jokerarroyo.net" );
call insertnewHouseMember("House Member", "Ramon", "A", "Rocamora", "Quezon City", "Siquijor", "Lone", "931 67 30", "931 50 01" );
call insertnewSenator("Senator", "Antero", "U", "Soriano", "Rm. 68 & 67 GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Member", "242-4356", "234-2342", "sorianoantero@gmail.com", "www.sorianoantero.ph" );
call insertnewSenator("Senator", "Leoncio", "B", "Imperial", "Rm. 565 & 15 GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Member", "234-4334", "232-7876", "ImperialLeo@gmail.com", "www.ImperialLeo.ph" );
call insertnewHouseMember("House Member", "Ann", "K", "Hofer", "Quezon City", "Bacolod City", "Lone", "931 57 22", "931 50 01" );
call insertnewHouseMember("House Member", "Arnolfo", "A", "Teves", "Quezon City", "Negros Occidental", "3rd", "931 56 10", "931 50 01" );
call insertnewHouseMember("House Member", "Ferdinand", "G", "Romualdez", "Quezon City", "North Cotabato", "1st", "442 40 39", "931 50 01" );
call insertnewSenator("Senator", "Pedro", "H", "Sison", "Rm. 543 & 7 (New Wing 5/F) GSIS Bldg., Financial Center, Diokno Blvd., Pasay City", "Member", "4566-6575", "345-2154", "pedro@gmail.com", "www.pedroS.ph" );
call insertnewHouseMember("House Member", "Jose", "I", "Tejada", "Quezon City", "North Cotabato", "3rd", "931 65 63", "931 50 01" );
call insertnewHouseMember("House Member", "Danilo", "E", "Suarez", "Quezon City", "Quezon",  "3rd", "931 54 48", "931 50 01" );
call insertnewSenator("Senator", "Sergio", "R", "Osmena III", "Rm. 517 & 10 (New Wing 5/F) GSIS Bldg., Financial Center, Diokno Blvd., Pasay City", "Member", "807-8489", "552-6776", "sergio.osmena@gmail.com", "www.sergioosmena.com" );
call insertnewSenator("Senator", "Camilo", "P", "Osias", "Rm. 5 & 13 (New Wing 5/F) GSIS Bldg., Financial Center, Diokno Blvd., Pasay City", "Member", "242-3453", "232-6575", "osiasC@gmail.com", "www.osiasC.ph" );
call insertnewHouseMember("House Member", "Gerald Anthony", "V", "Gullas", "Quezon City", "Cebu", "1st", "951 89 24", "931 50 01" );
call insertnewHouseMember("House Member", "Winston", "T", "Castelo", "Quezon City", "Quezon City", "2nd", "931 51 56", "931 50 01" );
call insertnewSenator("Senator", "Teresa", "K", "Aquino-Oreta", "Rm. 503 GSIS Bldg., Financial Center, Diokno Blvd., Pasay City", "Member", "345-6957", "552-6601", "terasaoreta@yahoo.com", "www.teresa.com" );
call insertnewSenator("Senator", "Emmanuel", "D", "Pacquiao", "Rm. 526 & 6 (New Wing 5/F) GSIS Bldg., Financial Center, Diokno Blvd., Pasay City", "Member", "552-6686", "552-6601", "sen.edpacquiao@gmail.com", "www.mannypacquiao.com.ph" );
call insertnewHouseMember("House Member", "Marlyn", "B", "Alonte", "Quezon City", "Biñan", "Lone", "931 61 96", "931 50 01" );
call insertnewSenator("Senator", "Joseph Victor" , "G", "Ejercito", "Rm. 511 & 2 (New Wing 5/F) GSIS Bldg., Financial Center, Diokno Blvd., Pasay City", "Member", "552-6748", "552-6601", "jvejercito@me.com", "www.jvejercito.com" );
call insertnewSenator("Senator", "Teofisto", "L", "Guingnoa", "Rm. 502 & 14 GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Member", "986-2001", "552-6601", "senatorguingona@gmail.com", "www.tgguingona.ph" );
call insertnewSenator("Senator", "Francisco", "R", "Enage", "Rm. 345 & 45 GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Member", "335-5432", "343-2342", "franciscoR@gmail.com", "www.frnaciscoR.ph" );
call insertnewSenator("Senator", "Jose", "M", "Generoso", "Rm. 234 & 09 GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Member", "632-5342", "345-4645", "generosoJose@gmail.com", "www.generosoJose.ph" );
call insertnewSenator("Senator", "Gloria", "M", "Arroyo", "Rm. 543 & 06 GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Member", "348-5644", "552-6601", "corruptpres@gmail.com", "www.gloryarroyo.com.ph" );
call insertnewHouseMember("House Member", "Rose Marie", "J", "Arenas", "Quezon City", "Pangasinan", "3rd", "931 56 67", "931 50 01" );
call insertnewHouseMember("House Member", "Anna", "K", "Pzifer", "Quezon City", "Zamboanga Sibugay", "2nd", "931 56 74", "931 50 01" );
call insertnewHouseMember("House Member", "Arnulfo", "P", "Fuentebella", "Quezon City", "Camarines Sur", "4th", "931 53 45", "931 50 01" );
call insertnewSenator("Senator", "Heherson", "T", "Alvarez", "Rm. 88 & 15 GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Member", "786-5432", "552-6601", "heherz@yahoo.com", "www.alva.net" );
call insertnewHouseMember("House Member", "Benhur", "L", "Salimbangon", "Quezon City", "Batangas", "6th", "951 10 27", "931 50 01" );
call insertnewSenator("Senator", "Juan", "A", "Villamor", "Rm. 235 & 7 (New Wing 5/F) GSIS Bldg., Financial Center, Diokno Blvd., Pasay City", "Member", "433-6575", "552-2154", "juan@gmail.com", "www.juanV.ph" );
call insertnewHouseMember("House Member", "Rene", "L", "Relampagos", "Quezon City", "Cavite", "2nd", "931 56 31", "931 50 01" );
call insertnewHouseMember("House Member", "Arthur", "C", "Yap", "Quezon City", "Bohol", "3rd", "931 54 26", "931 50 01" );
call insertnewSenator("Senator", "Teodoro", "P", "Guingona", "Rm. 345 & 13 (New Wing 5/F) GSIS Bldg., Financial Center, Diokno Blvd., Pasay City", "Member", "345-6957", "234-2154", "guingonaTeo@gmail.com", "www.guingonaTeo.ph" );
call insertnewSenator("Senator", "Miriam", "D", "Santiago", "Rm. 521-A GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Member", "552-6693", "552-6601", "miriam@miriam.com.ph", "www.miriam.com.ph" );
call insertnewSenator("Senator", "Manuel", "G", "Quezon", "Rm. 403 & 15 GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Member", "435-4301", "342-2342", "Qmanuel@gmail.com", "www.manuelquezon.ph" );
call insertnewSenator("Senator", "Ferdinand", "R", "Marcos Jr", "Rm. 518 GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Member", "552-3415", "552 6601", "info@bongbongmarcos.com", "www.bongbongmarcos.com" );
call insertnewHouseMember("House Member", "Emmeline", "Y", "Aglipay", "Quezon City", "South Cotabato", "1st", "931 66 91", "931 50 01" );
call insertnewSenator("Senator", "Santanina", "T", "Rasul", "Rm. 543 & 06 GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Member", "342-4645", "552-6601", "santan@yahoo.com", "www.santan.com.ph" );
call insertnewHouseMember("House Member", "Manuel", "F", "Zubiri", "Quezon City", "Bukidnon", "3rd", "951 89 57", "931 50 01" );
call insertnewSenator("Senator", "Teodoro", "Q", "Sandiko", "Rm. 732 & 7 (New Wing 5/F) GSIS Bldg., Financial Center, Diokno Blvd., Pasay City", "Member", "342-4645", "678-2154", "sandikoteodoro@gmail.com", "www.sandikoteodoro.ph" );
call insertnewHouseMember("House Member", "Sandra", "Y", "Eriguel", "Quezon City", "Rizal", "1st", "931 59 98", "931 50 01" );
call insertnewHouseMember("House Member", "Mercedes", "K", "Alvarez", "Quezon City", "Negros Occidental", "6th", "931 66 40", "931 50 01" );
call insertnewSenator("Senator", "Juan", "M", "Flavier", "Rm. 507 & 13 (New Wing 5/F) GSIS Bldg., Financial Center, Diokno Blvd., Pasay City", "Member", "552-6732", "552-6601", "javier@gmail.com", "www.javier.net" );
call insertnewSenator("Senator", "Espiridion", "M", "Guanco", "Rm. 765 & 09 GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Member", "632-2467", "234-9767", "espiridionguanco@gmail.com", "www.espiridionguanco.ph" );
call insertnewSenator("Senator", "Loren", "B", "Legarda", "Rm. 209-210 & 12 (New Wing 5/F) GSIS Bldg., Financial Center, Diokno Blvd., Pasay City", "Member", "833-1606", "552-6601", "loren@lorenlegarda.com.ph", "www.lorenlegarda.com.ph" );
call insertnewSenator("Senator", "Francis", "G", "Escudero", "Rm. 517 & 10 (New Wing 5/F) GSIS Bldg., Financial Center, Diokno Blvd., Pasay City", "Member", "833-5034", "552 6601", "sen.escudero@gmail.com", "www.chizescudero.com" );
call insertnewHouseMember("House Member", "Angelina", "E", "Tan", "Quezon City", "Quezon", "4th", "931 53 60", "931 50 01" );
call insertnewHouseMember("House Member", "Victor", "J", "Yu", "Quezon City", "San Juan City", "Lone", "442 40 32", "931 50 01" );
call insertnewSenator("Senator", "Gregorio", "L", "Honasan II", "Rm. 403 & 15 GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Member", "342-6957", "552-6601", "gregory@rocketmail.com", "www.greg.com.ph" );
call insertnewHouseMember("House Member", "Alfred", "D", "Vargas", "Quezon City", "Quezon City", "5th", "951 08 92", "931 50 01" );
call insertnewHouseMember("House Member", "Henry", "C", "Ong", "Quezon City", "Leyte", "2nd", "931 66 21", "931 50 01" );
call insertnewSenator("Senator", "Vicente", "C", "Sotto", "Rm. 603 & 24 (New Wing 5/F) GSIS Bldg., Financial Center, Diokno Blvd., Pasay City", "Majority Leader", "659-5259", "552-6601", "os_sotto@yahoo.com", " " );
call insertnewSenator("Senator", "Jose", "L", "Altavas", "Rm. 503 & 15 GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Member", "932-5432", "334-2342", "josealtavas@gmail.com", "www.joseAltavas.ph" );
call insertnewHouseMember("House Member", "Jorge", "N", "Banal", "Quezon City", "Quezon City", "3rd", "931 51 82", "931 50 01" );
call insertnewHouseMember("House Member", "Mark", "A", "Aglipay-Villar", "Quezon City", "Palawan", "3rd", "932 75 20", "931 50 01" );
call insertnewHouseMember("House Member", "Gus", "S", "Tambunting", "Quezon City", "Parañaque City", "2nd", "952 62 64", "931 50 01" );
call insertnewHouseMember("House Member", "Imelda", "Q", "Dimaporo", "Quezon City", "Lanao del Norte", "1st", "931 64 13", "931 50 01" );
call insertnewHouseMember("House Member", "Jennifer", "R", "Austria Barzaga", "Quezon City", "Cavite", "4th", "951 88 81", "931 50 01" );
call insertnewSenator("Senator", "Troadio", "D", "Galicano", "Rm. 11 & 7 (New Wing 5/F) GSIS Bldg., Financial Center, Diokno Blvd., Pasay City", "Member", "355-6786", "234-4334", "troadiogalicano@gmail.com", "www.troadiogalicano.ph" );
call insertnewHouseMember("House Member", "Pia", "S", "Cayetano", "Quezon City", "Taguig City-Pateros", "2nd", "951 88 91", "931 50 01" );
call insertnewSenator("Senator", "Juan Miguel", "F", "Zubiri", "Rm. 503 GSIS Bldg., Financial Center, Diokno Blvd., Pasay City", "Member", "986-2001", "552-6601", "migzubiri@gmail.com", "www.migzubiri.com.ph" );
call insertnewHouseMember("House Member", "Raul", "V", "Del Mar", "Quezon City", "Cavite", "3rd", "442 25 00", "931 50 01" );
call insertnewSenator("Senator", "Estebasn", "B", "Singson", "Rm. 565 & 15 GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Member", "932-4334", "232-4352", "SingsonE@gmail.com", "www.FilemonSotto.ph" );
call insertnewHouseMember("House Member", "Arlene", "B", "Arcillas", "Quezon City", "Laguna", "1st", "931 55 82", "931 50 01" );
call insertnewHouseMember("House Member", "Herminia", "B", "Roman", "Quezon City", "Antipolo City", "2nd", "442 40 34", "931 50 01" );
call insertnewSenator("Senator", "Neptali", "A", "Gonzales", "Rm. 68 & 67 GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Enforcer", "342-4645", "552-6601", "naptaline@gmail.com", "www.naptaline.com.ph" );
call insertnewHouseMember("House Member", "Manuel Luis", "T", "Lopez", "Quezon City", "Manila", "1st", "951 89 74", "931 50 01" );
call insertnewHouseMember("House Member", "Franz", "F", "Alvarez", "Quezon City", "Palawan", "1st", "931 54 69", "931 50 01" );
call insertnewHouseMember("House Member", "Isagani", "S", "Amatong", "Quezon City", "Zamboanga del Norte", "3rd", "931 57 46", "931 50 01" );
call insertnewHouseMember("House Member", "Isidro", "T", "Ungab", "Quezon City", "Misamis Oriental", "2nd", "931 56 79", "931 50 01" );
call insertnewSenator("Senator", "Blas", "F", "Ople", "Rm. 565 & 15 GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Member", "435-4301", "552-6601", "blasOble@yahoo.com", "www.ople.com" );
call insertnewSenator("Senator", "Rodolfo", "G", "Biazon", "Rm. 527 5th Flr., GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Member", "552-6703", "552-6601", "pongbiazon@yahoo.com", "www.biazon.net" );
call insertnewSenator("Senator", "Freddie", "M", "Webb", "Rm. 452 & 15 GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Member", "345-6957", "552-6601", "fredweb@rocketmail.com", "www.webbb.com.ph" );
call insertnewHouseMember("House Member", "Cheryl", "P", "Deloso-Montalla", "Quezon City", "Zambales", "2nd", "931 58 56", "931 50 01" );
call insertnewHouseMember("House Member", "Antonio", "L", "Tinio", "Quezon City", "Palawan", "2nd", "931 55 20", "931 50 01" );
call insertnewHouseMember("House Member", "Raul", "C", "Tupas", "Quezon City", "Iloilo", "5th", "442 51 22", "931 50 01" );
call insertnewSenator("Senator", "Jose", "D", "Clarin", "Rm. 21 & 7 (New Wing 5/F) GSIS Bldg., Financial Center, Diokno Blvd., Pasay City", "Member", "234-6786", "423-2344", "joseclarin@gmail.com", "www.joseclarin.ph" );
call insertnewSenator("Senator", "Jinggoy", "P", "Ejercito-Estrada", "Rm. 602 GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Member", " ", "552-6601", "senjinggoyestrada@senate.gov.ph", "www.senjinggoyestrada.com" );
call insertnewSenator("Senator", "Alejo", "O", "Mabanag", "Rm. 88 & 15 GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Member", "348-7976", "678-2342", "mabanagA@gmail.com", "www.mabanagA.ph" );
call insertnewSenator("Senator", "Joaquin", "D", "Luna", "Rm. 225 & 7 (New Wing 5/F) GSIS Bldg., Financial Center, Diokno Blvd., Pasay City", "Member", "234-6957", "423-2154", "joaquinluna@gmail.com", "www.joaquinLuna.ph" );
call insertnewSenator("Senator", "Lope", "O", "Santos", "Rm. 452 & 15 GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Member", "348-5644", "678-2342", "lopesantos@gmail.com", "www.lopesantos.ph" );
call insertnewSenator("Senator", "Pianco", "S", "Cay", "Rm. 523 & 14 (New Wing 5/F) G?SIS Bldg., Financial Center, Diokno Blvd., Pasay City", "Member", "807-8489", "552-6601", "alanpetercayetano.media@gmail.com", "www.alanpetercayetano.com" );
call insertnewSenator("Senator", "Juan", "P", "Enrile", "Rm. 601 GSIS Bldg., Financial Center, Roxas Blvd., Pasay City", "Minority Floor Leader", "807-8489", "552-6601", "senator_enrile@senate.gov.ph", "www.juanponceenrile.com" );